name: Rust

on: [push, pull_request]

env:
  YARN_CACHE_FOLDER: ./cache
  RUST_BACKTRACE: full

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
            git clone https://github.com/ankitects/anki . -b 24.06.3 --recursive
            git rev-parse --short=8 HEAD

      - name: Check
        run: |
            sudo apt update
            sudo apt install ninja-build curl build-essential git -y
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            ./tools/run-qt5.14
            ls -al

      - name: Check
        run: |
            ./yarn install --ignore-scripts
            ls -al

      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: aarch64
          distro: buster

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # The shell to run commands with in the container
          shell: /bin/bash

          env: | # YAML, but pipe character is necessary
            RUST_BACKTRACE: full
            YARN_CACHE_FOLDER: ./cache

          # Produce a binary artifact and place it in the mounted volume
          run: |
            apt update
            apt install ninja-build curl build-essential git -y
            git config --global --add safe.directory ${PWD}
            git rev-parse --short=8 HEAD
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            rustc --version
            cargo --version
            ./tools/run-qt5.14
            cp ./out /artifacts/ -r

      - name: Upload out directory
        uses: actions/upload-artifact@v3
        with:
          name: out-files
          path: "${PWD}/artifacts/out"
