name: Rust

on: [push, pull_request]

env:
  YARN_CACHE_FOLDER: ./cache
  RUST_BACKTRACE: full

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
            git clone https://github.com/ankitects/anki . -b 24.06.3 --recursive
            git rev-parse --short=8 HEAD

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: test:latest
          platforms: linux/arm64

      - name: Upload out directory
        uses: actions/upload-artifact@v3
        with:
          name: out-files
          path: "${PWD}/artifacts/out"
