name: Rust

on: [push, pull_request]

env:
  YARN_CACHE_FOLDER: ./cache
  RUST_BACKTRACE: full

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
                Dockerfile
          sparse-checkout-cone-mode: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.actor }}/test:${{ github.run_number	}}
          # platforms: linux/arm64

  pull_docker_image:
    runs-on: ubuntu-latest
    needs: build_job  
    
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Pull Docker image
        run: |
          container_id=$(docker create "ghcr.io/${{ github.actor }}/test:${{ github.run_number	}}")
          docker cp "$container_id:/data/out/wheels" "."
          docker rm "$container_id"
      - uses: actions/upload-artifact@v4
        with: 
          path: ./wheels
