name: Rust

on: [push, pull_request]

jobs:
  build_job:
    # The host should always be linux
    runs-on: macos-latest
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ankitects/anki
          path: anki

      - name: Set up Docker
        run: |
          docker pull debian:10

      - name: Run in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/anki:/app -w /app debian:10 bash -c "
          apt-get update && \
          apt-get install -y rustc cargo ninja-build && \
          ./tools/run-qt5.15
          "

      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: anki/out