name: Rust

on: [push, pull_request]

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: aarch64
          distro: buster

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # The shell to run commands with in the container
          shell: /bin/bash

          env: | # YAML, but pipe character is necessary
            RUST_BACKTRACE: 1

          # Produce a binary artifact and place it in the mounted volume
          run: |
            apt update
            apt install ninja-build curl build-essential git -y
            git clone https://github.com/ankitects/anki . -b 24.06.3 --recursive
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            rustc --version
            cargo --version
            ./run
            cp ./out /artifacts/ -r

      - name: Upload out directory
        uses: actions/upload-artifact@v3
        with:
          name: out-files
          path: "${PWD}/artifacts/out"
