name: Rust

on: [push, pull_request]

env:
  YARN_CACHE_FOLDER: ./cache
  RUST_BACKTRACE: full

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
                Dockerfile
          sparse-checkout-cone-mode: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: test:latest
          platforms: linux/arm64

      - name: Copy out directory from the image
        run: |
          docker create --name temp-container test:latest
          docker cp temp-container:/data/out ./out
          docker rm temp-container

      - name: Upload out directory
        uses: actions/upload-artifact@v3
        with:
          name: out-files
          path: "${PWD}/out"
